### ISSUE TITLE
Change LightGraphs.jl dependency to Graphs.jl

### ISSUE THREAD

**Issue by simonschoelly** [rkurchin/Nodariety.jl#11]
This came up here: https://github.com/JuliaGraphs/NetworkLayout.jl/pull/58 - maybe it is time to update this package to Graphs.jl? Let us know if you need help there.

**Comment by rkurchin** [comment]
Thanks! Yes, I could definitely stand to do that and will do so when I find some time – this was sort of a fun side project and nothing (to my knowledge) depends on it, so it's not really urgent, but thanks a lot for catching this and letting me know!

**Comment by rkurchin** [comment]
[Finally fixed!](https://github.com/rkurchin/Nodariety.jl/commit/8ec2ab3a4bbb4776927ab381a966391290badc67)
